blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, LikeView, CreateComment, UserPostListView
from django.contrib.auth.models import User
from . import views


urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),

    path('user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    
    path('post/<str:pk>/', PostDetailView.as_view(), name='post-detail'),

    # path('post/<str:pk>/', views.single_post, name='post-detail'),

    path('post-form/', PostCreateView.as_view(), name='post-create'), 

    path('article/<int:pk>/comment/', CreateComment.as_view(), name='add_comment'), 

    path('search-post/', views.search_post, name='search_post'), 
    
    path('post/<str:pk>/update/', PostUpdateView.as_view(), name='post-update'),

    path('post/<str:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

    path('category/<category>/', views.CatListView.as_view(), name='category'),

    path('archive/<archive>/', views.ArchiveListView.as_view(), name='archive'),

    # on post id -->  path('post/<slug:slug:text>'),
    path('about/', views.about, name='about-page'),
  
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views

from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('blog.urls')),

    path('account/', include('users.urls', namespace='accounts')),

    path('account/', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

from .forms import UserLoginForm

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html', authentication_form=UserLoginForm), name='login'),

    path('logout/', views.logout, name='logout'),
    path('register/', views.registerPage, name='register'),

    path('profile/', views.profilePage, name='profile'),
    path('update-profile/', views.updateProfile, name='update-profile'),

    path('like/', views.like, name='like'),
    
    path('bookmark/<str:id>/', views.bookmark_add, name='bookmark_add'),
    path('bookmarks/', views.bookmark_list, name='bookmark_list'),
]

blog/models.py
from django.db import models
from django.db.models.deletion import CASCADE

from cloudinary.models import CloudinaryField
from django.db.models.fields.related import ManyToManyField

from django.db.models.signals import pre_save
from django_blog.utils import unique_slug_generator
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class BookmarkManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset() .filter()

class Post(models.Model):
    title = models.CharField(max_length=200, null=True)
    location = models.CharField(max_length=255, null=True)
    category = models.ForeignKey('Category', null=True, on_delete=models.PROTECT, default=1)
    
    archive = models.ForeignKey('Archive', null=True, on_delete=models.PROTECT, default=1)
    slug = models.SlugField(max_length=255, unique=True, null=True, blank=True)
    content = models.TextField()
    image = CloudinaryField(default = 'default.jpg')
    image_caption = models.CharField(max_length = 100, default = 'Photo by Blog')
    
    date_posted = models.DateTimeField(default=timezone.now)
    published = models.BooleanField(default=False)
    favourites = models.ManyToManyField(User, related_name='favourite', default=None, blank=True)
    likes = models.ManyToManyField(User, related_name='likes', default=None, blank=True)
    like_count = models.BigIntegerField(default='0')


    author = models.ForeignKey(User, on_delete=CASCADE)
    tags = models.ManyToManyField('Tag', blank=True)
    objects = models.Manager()  # default manager
    bookmarkmanager = BookmarkManager()  # custom manager
    # dunder str method
    def __str__(self):
        return self.title

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

class Category(models.Model):
    name = models.CharField(max_length=200, null=True)
    image = CloudinaryField(default = 'default.jpg')
    date_posted = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.name

    def __unicode__(self):
        return


class Archive(models.Model):
    name = models.CharField(max_length=400, null=True)
    image = CloudinaryField(default = 'default.jpg')
    date_posted = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.name

    def __unicode__(self):
        return


class Comment(models.Model):
    name = models.CharField(max_length=255, default=None )
    post = models.ForeignKey(Post, on_delete=models.CASCADE,default=None, related_name='comments')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.name)
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name
    
    def __unicode__(self):
        return 

blog/forms.py
from django import forms

from django.contrib.auth.models import User
from django.forms import widgets

from .models import Comment

class CreateComment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'body']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            # derrick macharia
            # 
        }

blog/views.py
from django.contrib.auth import login
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CreateComment

from .models import *
# Create your views here.

#
def home(request):
    context = { 'posts' : Post.objects.all()}
    return render(request, 'blog/home.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html' #<app> / <model> <viewtype>.html
    context_object_name = 'posts' # naming the varible
    ordering = ['-date_posted']
    paginate_by = 8

    def post(self, *args, **kwargs):
        self.object = self.get_object()

        if self.object.bookmark.filter(id=request.user.id).exists():
            self.object.bookmark.remove(request.user)
        else:
            self.object.bookmark.add(request.user)

        return redirect('blog-home', pk=self.object.pk)



class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html' #<app> / <model> <viewtype>.html
    context_object_name = 'posts' # naming the varible
    paginate_by = 8

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')

  
# def single_post(request, pk):

#     single_post = Post.objects.get(id = pk)

#     context = {'single_post': single_post}

#     return render(request, 'blog/single.html', context)



class PostDetailView(DetailView):
    model = Post
    extra_context ={'comment': Comment.objects.all()}
    


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title','location','category','content','image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog-home')
    

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title','location','category', 'tags', 'content','image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

    def get_success_url(self):
        return reverse_lazy('blog-home')
    

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
   
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

    def get_success_url(self):
        return reverse_lazy('blog-home')
    


class ArchiveListView(ListView):
    template_name = 'blog/archive.html'
    context_object_name = 'archlist'

    def get_queryset(self):
        content = {
            'arch': self.kwargs['archive'],
            'posts': Post.objects.filter(archive__name=self.kwargs
            ['archive'])
        }
        return content

def archive_list(request):

    archive_list = Archive.objects.exclude(name='default')
    context = {
        'archive_list':archive_list
        }
    return context

class CatListView(ListView):
    template_name = 'blog/category.html'
    context_object_name = 'catlist'

    def get_queryset(self):
        content = {
            'cat': self.kwargs['category'],
            'posts': Post.objects.filter(category__name=self.kwargs
            ['category'])
        }
        return content

def category_list(request):

    category_list = Category.objects.exclude(name='default')
    context = {
        'category_list':category_list
        }
    return context

class CreateComment(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CreateComment
    template_name = 'blog/add_comment.html'

    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)
    success_url = reverse_lazy('blog-home')


def search_post(request):
    if request.method == 'POST':
        search = request.POST['search']
        search_post = Post.objects.filter(title__contains=search)
        return render(request, 'blog/search.html',{'search':search, 'search_post':search_post})
    else:
        return render(request, 'blog/search.html', {'title': 'About'})



@login_required
def LikeView(request,pk):
    post = get_object_or_404(Post, id = request.POST.get('post_id'))
    post.likes.add(request.user)
    return HttpResponseRedirect(reverse('post-detail', args=[str(pk)]))


@login_required
def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})

blog/templates/blog/about.html
{% extends 'blog/main.html' %}
{% block content %}
    <h1>About</h1>
{% endblock content %}

blog/templates/blog/add_comment.html
{% extends 'blog/main.html' %} {% load static %} {% load crispy_forms_tags %} {% block content %}
<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}
<style>
    form {
        margin-left: 25px;
    }
</style>
<div id="main">
    <article class="post">
        <header>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <h2 class="border-bottom mb-4">Create Comment</h2>
                    {{ form|crispy }}

                </fieldset>
                <div class="form-group" style="margin-top: 5px;">
                    <button class="btn btn-outline-info" type="submit">Comment</button>
                </div>
            </form>
        </header>
    </article>
</div>

{% endblock content %}

blog/templates/blog/bookmark.html
{% extends 'blog/main.html' %} {% load static %} {% block content %}


<div id="main">
    {% for post in new %}
    <!-- Post -->
    <article class="post">
        <header>
            <div class="title">
                <h2><a href="{% url 'post-detail' post.id %}"> {{ post.title | truncatechars:25}} </a></h2>
                <p><a href="#"> {{ post.category }} </a></p>
            </div>
            <div class="meta">
                <time class="published" datetime="2015-11-01"> {{ post.date_posted |date:"F d, Y" }}</time>
                <a href=" {% url 'accounts:profile' %} " class="author"><span class="name"> {{ post.author }} </span><img src=" {{ post.author.profile.profile_pic.url }} " alt="" /></a>
            </div>
        </header>
        <a href="" class="image featured" style="object-fit: cover;"><img src=" {{ post.image.url }} " alt="" /></a>
        <p> {{ post.content| truncatechars:100}} </p>
        <footer>
            <ul class="actions">
                <li><a href="{% url 'post-detail' post.id %}" class="button large">Continue Reading </a></li>
                <!-- change id attribute to slug -->
            </ul>
            <ul class="stats">
                <li><a href="#">General</a></li>
                <li><a href="#" class="icon solid fa-heart">28</a></li>
                <li><a href="#" class="icon solid fa-comment">128</a></li>
                <li>
                    <a href=" {% url 'accounts:bookmark_add' post.id %} " class="icon solid fa-bookmark"></a>
                </li>
            </ul>
        </footer>
    </article>
    {% endfor %}
    <!-- Pagination -->
    <ul class="actions pagination">
        <li><a href="" class="disabled button large previous">Previous Page</a></li>
        <li><a href="#" class="button large next">Next Page</a></li>
    </ul>

</div>

{% endblock content %}

blog/templates/blog/home.html
{% extends 'blog/main.html' %} {% load static %} {% block content %}

<div id="main">
    {% for post in posts %}
    <!-- Post -->
    <article class="post">
        <header>
            <div class="title">
                <h2><a href="{% url 'post-detail' post.id %}"> {{ post.title | truncatechars:25}} </a></h2>
                <p><a href="#">{{ post.category }}</a></p>
            </div>
            <div class="meta">
                <time class="published" datetime="2015-11-01"> {{ post.date_posted |date:"F d, Y" }}</time>
                <a href=" {% url 'user-posts' post.author.username %} " class="author"><span class="name"> {{ post.author }} </span>
                    {% if post.author.profile.profile_pic %}
                    <img src=" {{ post.author.profile.profile_pic.url }} " alt="" /></a> {% else %}
                <img src="{% static 'images/person_1.jpg' %}"> {% endif %}
            </div>
        </header>
        <a href="{% url 'post-detail' post.id %}" class="image featured" style="object-fit: cover;"><img src=" {{ post.image.url }} " alt="" /></a>
        <p> {{ post.content| truncatechars:150}} </p>
        <footer>
            <ul class="actions">
                <li><a href="{% url 'post-detail' post.id %}" class="button large">Continue Reading </a></li>
                <!-- change id attribute to slug -->
            </ul>
            <ul class="stats">
                <li><a href="#">General</a></li>
                <li><a href="#" class="icon solid fa-heart">{{post.like_count}}</a></li>
                {% if user.is_authenticated %}
                <li><a href=" {% url 'add_comment' post.pk %} " class="icon solid fa-comment"> 44</a></li>
                {% else %}
                <li>
                    <a href=" {% url 'accounts:register' %} " class="icon solid fa-bookmark"></a>
                </li>
                {% endif %} {% if user.is_authenticated %}
                <li>
                    <a href=" {% url 'accounts:bookmark_add' post.id %} " class="icon solid fa-bookmark"></a>
                </li>
                {% else %}
                <li>
                    <a href=" {% url 'accounts:register' %} " class="icon solid fa-bookmark"></a>
                </li>
                {% endif %}
            </ul>
        </footer>
    </article>
    {% endfor %}
    <!-- Pagination -->
    <ul class="actions pagination">
        {% if is_paginated %} {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}" class="button large previous">Previous Page</a></li>
        {% endif %} {% if page_obj.has_next %}
        <li><a href=" ?page={{ page_obj.next_page_number }} " class="button large next">Next Page</a></li>
        {% endif %} {% endif %}
    </ul>

</div>

{% endblock content %}

blog/templates/blog/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- ====== CSS ======-->
    <link rel="stylesheet" href=" {% static 'assets/css/main.css' %} " />
    <!-- ====== Title ======-->
    {% if title %}
    <title>Django Blog - {{ title }}</title>
    {% else %}
    <title>Django Blog</title>
    {% endif %}
</head>

<body class="is-preload">

    {% include 'blog/navbar.html' %}

    <div id="wrapper">

        {% block content %} {% endblock content %} {% include 'blog/sidebar.html' %}

    </div>

</body>
<!-- ====== JS ======-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src=" {% static 'assets/js/jquery.min.js' %}"></script>
<script src=" {% static 'assets/js/browser.min.js' %} "></script>
<script src=" {% static 'assets/js/breakpoints.min.js' %} "></script>
<script src=" {% static 'assets/js/util.js' %} "></script>
<script src=" {% static 'assets/js/main.js' %} "></script>
<script>
    function formExit() {
        document.getElementById("newForm").remove();
    }

    function myFunction(id) {
        if (document.contains(document.getElementById("newForm"))) {
            document.getElementById("newForm").remove();
        }

        var d1 = document.getElementById(id);
        d1.insertAdjacentHTML('afterend',
            '<form id="newForm" class="form-insert py-2" method="post"> \
                   <textarea name="content" cols="40" rows="5" class="form-control" required id="id_content"></textarea> \
                  {% csrf_token %} \
                  <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button> \
                </form>');
    }

    $('#myForm').trigger("reset");

    $(document).on('click', '#like-button', function(e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "accounts:like" %}',
            data: {
                postid: $('#like-button').val(),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success: function(json) {
                document.getElementById("like_count").innerHTML = json['result']
            },
            error: function(xhr, errmsg, err) {

            }
        });
    })
</script>

</html>

blog/templates/blog/navbar.html
{% load static %}
<!-- Header -->
<header id="header">
    <h1><a href=" {% url 'blog-home' %} ">Future Allure</a></h1>
    <nav class="links">
        <ul>
            <li><a href=" {% url 'blog-home' %} ">Home</a></li>
            {% for category in category_list %}
            <li><a href="/category/{{category.name}}"> {{ category.name }} </a></li>
            {% endfor %}
        </ul>
    </nav>
    <nav class="main">
        <ul>
            <li class="search">
                <a class="fa-search" href="#search">Search</a>

                <form id="search" method="POST" action=" {% url 'search_post' %} ">
                    {% csrf_token %}
                    <input type="text" name="search" placeholder="Search" />
                </form>
            </li>
            <li class="menu">
                <a class="fa-bars" href="#menu">Menu</a>
            </li>
        </ul>
    </nav>
</header>

<!-- Menu -->
<section id="menu">

    <!-- Search -->
    <section>
        <form class="search" method="POST" action=" {% url 'search_post' %} ">
            {% csrf_token %}
            <input type="text" name="search" placeholder="Search" />
        </form>
    </section>

    <!-- Links -->
    <section>
        <ul class="links">
            <li>
                <a href=" {% url 'post-create' %}">
                    <h3>Post a blog</h3>
                    <p> Tell your amazing story </p>
                </a>
            </li>
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'accounts:bookmark_list' %} ">
                    <h3>Bookmarks</h3>
                    <p>Saves Posts</p>
                </a>
            </li>
            <li>
                <a href=" {% url 'accounts:profile' %} ">
                    <h3>Design Your Profile</h3>
                    <p>Update</p>
                </a>
            </li>

            {% else %}
            <li>
                <a href="{% url 'accounts:bookmark_list' %} ">
                    <h3>Bookmarks</h3>
                    <p>Saves Posts</p>
                </a>
            </li>
            <li>
                <a href=" {% url 'login' %} ">
                    <h3>Login</h3>
                    <p>Access your Account</p>
                </a>
            </li>
            <li>
                <a href=" {% url 'accounts:register' %} ">
                    <h3>Register</h3>
                    <p>Create an Account</p>
                </a>
            </li>
            {% endif %}
        </ul>
    </section>

    <!-- Actions -->
    <section>
        {% if user.is_authenticated %}
        <ul class="actions stacked ">
            <li><a href=" {% url 'logout' %} " class="button large fit ">Log Out</a></li>
        </ul>
        {% endif %}
    </section>

</section>

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/main.html' %} {% load static %} {% block content %}
<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}
<div id="main">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Post</legend>
            <h2>Are you sure you want to delete the post "{{object.category}}" ? </h2>
        </fieldset>
        <div class="form-group" style="margin-top: 5px;">
            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>

            <a class="btn btn-outline-danger" href=" {% url 'post-detail' object.id %} ">Cancel</button>
        </div>
    </form>
 </div>
            
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/main.html' %} {% load static %} {% block content %}
<style>
    .like_btn,
    button,
    submit {
        border: none;
        outline: none;
        font-size: 0.9em;
        background: none;
    }
</style>
<div id="main">

    <!-- Post -->
    <article class="post">
        <header>
            <div class="title">
                <h2>{{ object.title }}</h2>
                <p> {{ object.location }} </p>
            </div>
            <div class="meta">
                <time class="published" datetime="2015-11-01"> {{ object.date_posted |date:"F d, Y" }}</time>
                <a href=" {% url 'user-posts' object.author.username %} " class="author"><span class="name"> {{ object.author }} </span>
                    {% if post.author.profile.profile_pic %}
                    <img src=" {{ post.author.profile.profile_pic.url }} " alt="" /></a> {% else %}
                <img src="{% static 'images/person_1.jpg' %}"> {% endif %}
            </div>
        </header>
        <a href="" class="image featured" style="object-fit: cover;"><img src=" {{ object.image.url }} " alt="" /></a>
        <p> {{ object.content }} </p>
        <footer>
            <ul class="stats">
                {% if object.author == user %}
                <li><a href=" {% url 'post-update' object.id %} ">Update</a></li>
                {% endif %} {% if request.user.is_authenticated %}
                <button class="like_btn" id="like-button" value="{{post.id}}">
                    <li><a id="like_count" class="icon solid fa-heart">{{post.like_count}}</a></li>
                  </button> {% else %}

                <li><a href="{% url 'accounts:register' %}" class="icon solid fa-heart">{{post.like_count}}</a></li>
                {% endif %} {% if user.is_authenticated %}
                <li><a href=" {% url 'add_comment' post.pk %} " class="icon solid fa-comment"> {{ comment.count }} </a></li>
                {% else %}
                <li>
                    <a href=" {% url 'accounts:register' %} " class="icon solid fa-bookmark"></a>
                </li>
                {% endif %}
                <li>
                    <a href="#" class="icon solid fa-bookmark"></a>
                </li>
            </ul>
        </footer>
    </article>

    <!-- Comment Section  -->
    {% if not post.comments.all %}
    <article class="post">
        <header>
            <div class="title">
                <h2>No Comment...</h2>
            </div>
        </header>
    </article>

    {% else%} {% for comment in post.comments.all %}
    <article class="post">
        <header>
            <div class="title">
                <h3> {{comment.name}} </h3>
                <p> {{ comment.body }} </p>
            </div>
            <div class="meta">
                <time class="published" datetime="2015-11-01"> {{ comment.publish |date:"F d, Y" }}</time>
                <a href="#" class="author"><span class="name"> {{ object.author }} </span><img src=" {{ post.author.profile.profile_pic.url }} " alt="" /></a>
            </div>
        </header>
    </article>
    {% endfor %} {% endif %}
</div>

{% endblock content %}

blog/templates/blog/search.html
{% extends 'blog/main.html' %} {% load static %} {% block content %}


<div id="main">
    
 {% if search %}

 {% for post in search_post %}
    <!-- Post -->
    <article class="post">
        <header>
            <div class="title">
                <h2><a href="{% url 'post-detail' post.id %}"> {{ post.title | truncatechars:25}} </a></h2>
                <p><a href="#"> {{ post.category }} </a></p>
            </div>
            <div class="meta">
                <time class="published" datetime="2015-11-01"> {{ post.date_posted |date:"F d, Y" }}</time>
                <a href=" {% url 'accounts:profile' %} " class="author"><span class="name"> {{ post.author }} </span><img src=" {{ post.author.profile.profile_pic.url }} " alt="" /></a>
            </div>
        </header>
        <a href="" class="image featured" style="object-fit: cover;"><img src=" {{ post.image.url }} " alt="" /></a>
        <p> {{ post.content| truncatechars:100}} </p>
        <footer>
            <ul class="actions">
                <li><a href="{% url 'post-detail' post.id %}" class="button large">Continue Reading </a></li>
                <!-- change id attribute to slug -->
            </ul>
            <ul class="stats">
                <li><a href="#">General</a></li>
                <li><a href="#" class="icon solid fa-heart">28</a></li>
                <li><a href="#" class="icon solid fa-comment">128</a></li>
                {% if user.is_authenticated %}
                <li><a href=" {% url 'accounts:bookmark_add' post.id %} " class="icon solid fa-bookmark"></a></li>
                {% else %}
                <li><a href=" {% url 'accounts:register' %} " class="icon solid fa-bookmark"></a></li>
                {% endif %}
            </ul>
        </footer>
    </article>
    {% endfor %}

 {% else %}

<h1>There is nothing that you've searched for</h1>

{% endif %}


</div>

{% endblock content %}

blog/templates/blog/user_posts.html
{% extends 'blog/main.html' %} {% load static %} {% block content %}

<div id="main">
    <h3> Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }}) </h3>
    {% for post in posts %}
    <!-- Post -->
    <article class="post">
        <header>
            <div class="title">
                <h2><a href="{% url 'post-detail' post.id %}"> {{ post.title | truncatechars:25}} </a></h2>
                <p><a href="#"> {{ post.tags }} </a></p>
            </div>
            <div class="meta">
                <time class="published" datetime="2015-11-01"> {{ post.date_posted |date:"F d, Y" }}</time>
                <a href=" {% url 'user-posts' post.author.username %} " class="author"><span class="name"> {{ post.author }} </span>
                    {% if post.author.profile.profile_pic %}
                    <img src=" {{ post.author.profile.profile_pic.url }} " alt="" /></a> {% else %}
                <img src="{% static 'images/person_1.jpg' %}"> {% endif %}
            </div>
        </header>
        <a href="{% url 'post-detail' post.id %}" class="image featured" style="object-fit: cover;"><img src=" {{ post.image.url }} " alt="" /></a>
        <p> {{ post.content| truncatechars:150}} </p>
        <footer>
            <ul class="actions">
                <li><a href="{% url 'post-detail' post.id %}" class="button large">Continue Reading </a></li>
                <!-- change id attribute to slug -->
            </ul>
            <ul class="stats">
                <li><a href="#">General</a></li>
                <li><a href="#" class="icon solid fa-heart">{{post.like_count}}</a></li>
                {% if user.is_authenticated %}
                <li><a href=" {% url 'add_comment' post.pk %} " class="icon solid fa-comment">128</a></li>
                {% else %}
                <li>
                    <a href=" {% url 'accounts:register' %} " class="icon solid fa-bookmark"></a>
                </li>
                {% endif %} {% if user.is_authenticated %}
                <li>
                    <a href=" {% url 'accounts:bookmark_add' post.id %} " class="icon solid fa-bookmark"></a>
                </li>
                {% else %}
                <li>
                    <a href=" {% url 'accounts:register' %} " class="icon solid fa-bookmark"></a>
                </li>
                {% endif %}
            </ul>
        </footer>
    </article>
    {% endfor %}
    <!-- Pagination -->
    <ul class="actions pagination">
        {% if is_paginated %} {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}" class="button large previous">Previous Page</a></li>
        {% endif %} {% if page_obj.has_next %}
        <li><a href=" ?page={{ page_obj.next_page_number }} " class="button large next">Next Page</a></li>
        {% endif %} {% endif %}
    </ul>

</div>

{% endblock content %}